### ISSUE TITLE
AppDbContext and Nullability

### ISSUE THREAD

**Issue by mmwoodfo** [IntelliTect/CodingGuidelines#113]
An `AppDbContext` has non-nullable 'DbSet<T>' properties as in:
```
public class AppDbContext : DbContext 
{
        public DbSet<ApplicationUser> ApplicationUsers { get; set; };
        public DbSet<AuditLog> AuditLogs { get; set; };
        public DbSet<Wiki> Wikis { get; set; };
        public DbSet<Page> Pages { get; set; };
        public IDatabaseOperationContext OperationContext { get; set; };
        // ...
}
```

According to the Microsoft documentation, nullabillity warnings should be disabled by assigning `null!` - see https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types.  This, however, doesn't match our coding guidelines.  

Since we presumably don't want these sets to ever be assigned null, is it reasonable to use our standards - thereby checking for null and throwing an exception in the setter, or should this be an exception?

**Comment by Keboo** [comment]
Rather than doing `null!` there are a couple more preferable alternatives we would like to investigate.

1. Suppressing the warning using `#pragma disable` around the DbSets. 
2. Create singleton empty `DbSet` and assign that as the default.

**Comment by ascott18** [comment]
The `DbSet` properties on a context would never be getting manually assigned to anything. They get automatically created by the `DbContext` class when instantiated, and there's no compelling reason that anyone would ever assign anything else to them. I can say for sure that I've never seen anyone do something like this.

I would say the official Microsoft recommendations here trump our coding guidelines. However, on top of that, my personal preference would to wrap them all in a `#nullable disable` `#nullable restore` because this is a case where C# 8 nullability just isn't useful, and it avoids having to copy/paste the same exact code on every single property (whether that be `= null!;`, or something else)

**Comment by MarkMichaelis** [comment]
Until or unless there is a way for the `DbSet` properties to be read only and set in the constructor, I agree with this recommendation.  It is preferable to assigning `null!`.

**Comment by ascott18** [comment]
I guess making the setters `protected` would add some level of defense and shouldn't cause EF any issues. Again though, having the DbSets set to null is something that I've never ever seen, either accidentally or intentionally.

**Comment by Keboo** [comment]
I believe the preferable approach should be to use the `#pragma` to disable the warning in these cases. Key points:
- `= null!` is misleading as the property will be set via reflection (pretty sure this occurs in the base class constructor).
- Outside of a direct assignment of `null` to the property there is no way for it to ever be `null`. However, these cases are likely mitigated by any amount of reasonable unit testing.
- The `#nullable disable` returns the property back to its pre-C# 8 state which is null-ability Unknown. This also causes the compiler to not output the nullability attribute on the properties.
- The `#pragma`  disabling of the warning, leaves the nullability state of not-nullable in place, and simply tells the compiler to not output the warning.

Given the above, I would propose the `#pragma` as the best option, even over the MS suggestion.

**Comment by MarkMichaelis** [comment]
I wasn't paying attention.  Thanks Kevin, I agree, #praga is preferable.

**Comment by Keboo** [comment]
We should document on the web site, the preference for using the `#pragma` to disable the warning and include the reasoning above (or link to this issue).

**Comment by Keboo** [comment]
As per MS [latest recommendation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#dbcontext-and-dbset) the solution should be to reference the base Set<T> method for your DB Sets.

We should include a link to the MS docs to make these more obvious to others.
```
public class AppDbContext : DbContext 
{
        public DbSet<ApplicationUser> ApplicationUsers => Set<ApplicationUser>()
        public DbSet<AuditLog> AuditLogs => Set<AuditLog>();
        public DbSet<Wiki> Wikis => Set<Wiki>();
        public DbSet<Page> Pages => Set<Page>();
        // ...
}
```

**Comment by ascott18** [comment]
MS's latest latest recommendation, per the results of running `dotnet ef dbcontext scaffold`, is a blanket `#nullable disable` on the whole DbContext class..

**Comment by Keboo** [comment]
@ascott18 any objection to having our recommendation be to point to the EF [docs page](https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types#dbcontext-and-dbset)?

Or would you like to have a meeting to discuss?

**Comment by ascott18** [comment]
No, that's fine. I actually later found out that the blanket disable was just a bandaid fix since they haven't yet added nullability support for scaffolded output yet. https://github.com/dotnet/efcore/issues/15520

**Comment by Keboo** [comment]
Closing for now. The recommendation is to follow the guidelines from the EF Core team.
