### ISSUE TITLE
Automate generation of coding standards

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingGuidelines#115]
Currently the guidelines that are posted are out of date and we need to get them updated.

**Comment by twofingerrightclick** [comment]
I added a branch with a csv of all the guidelines. You can work with it as you please.

**Comment by Keboo** [comment]
Next steps on this, we would like to work on mapping the CSV into the documentation pages.

We think the next approach is to build something similar to the following:
- [ ] A second file that contains the mapping between the book ids, and the corresponding heading titles (we have two levels of nesting)
- [ ] A pipeline that triggers whenever the CSV or mapping file is modified.
- [ ] The pipeline should generate the `docs\coding\csharp.md` file
- [ ] The pipeline should open a PR if there are any changes to the `docs\coding\csharp.md` file (@Keboo has a working example of this)

### Bonus points:
- Correctly syntax highlight C# code inside of the coding standards.
- Correctly identify the correct emoji for each of the coding standards (`:heavy_check_mark:`, `:no_entry:`, etc).
- Allow for the mapping file to contain additional markdown for adding explanations to rules.
