### ISSUE TITLE
Create IntelliTect.Snippets VSIX

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingGuidelines#116]
We want to have a convenient way to share code snippets so we will create a new VSIX package to contain the snippets. As a MVP it should contain the snippet from #114 

We should have a pipeline that automatically publishes updates when there are changes to the snippets folder.

We should document in the README so people know how to get the VSIX and the appropriate settings to keep it updated.
![image](https://user-images.githubusercontent.com/952248/85613799-19b0c000-b60f-11ea-9df2-23574a226285.png)

**Comment by twofingerrightclick** [comment]
Here is a solution to that idea: https://github.com/IntelliTect/IntelliTect.Snippets
