### ISSUE TITLE
Build production site

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingGuidelines#122]
Right now everything that merges becomes live and doesn't allow us to preview changes ahead of time.

What we think we want to do:

- [x] Create a second repository in IntelliTect to host the new site. Its contents will be that of the `docs/` directory from here. This repository effectively becomes the staging environment. 
- [x] Define explicit action that needs to be taken on this repository to cause "production" to be updated. Tagging/Branching/Release/etc.
- [x] Create github action on this repository that can trigger on explicit action and copy over the relevant files to the new repository.
- [x] Validate that the new repository has the same URL that is currently present here. 
- [ ] Update the URL here to contain "staging".

**Comment by edmondsb** [comment]
https://github.com/marketplace/actions/copycat-action?version=v3.2.3
https://github.com/marketplace/actions/string-replace
I think that these two actions could work for this. I tested the copycat action on my own cloned version of this repo and was able to build the website from the copied docs folder after changing the site settings, and the url.
The string replace action could be added to the production repo that would change the base url and url to match what it currently is.

**Comment by Keboo** [comment]
@edmondsb that looks like a great way to do it. Do you want to take on implementing this?

**Comment by edmondsb** [comment]
Today is actually my last day for the summer, but Austin said he was interested.

**Comment by Keboo** [comment]
There is a new repo located here:
https://github.com/IntelliTect/CodingGuidelinesSite/

We need to get GitHub pages working here.

**Comment by twofingerrightclick** [comment]
The copy action is in place:
https://github.com/IntelliTect/CodingGuidelines/actions?query=workflow%3A%22Update+Docs+Folder+on+CodingGuidelinesSite%22

**Comment by twofingerrightclick** [comment]
I changed the intellitect.com redirect:
![image](https://user-images.githubusercontent.com/11265760/98312691-1ba86980-1f87-11eb-85a1-0eee50fcb8f9.png)

**Comment by twofingerrightclick** [comment]
1. Whenever a commit to master involves a change to the guidelines xml file a new markdown file is created.
2. A manual action can be run from the CodingGuidelines repo that will then update the CodingGuidelinesSite repo which is hosting the production site.

**Comment by BenjaminMichaelis** [comment]
Is there anything holding us to using github pages to deploy site? 

If not we could use [netlify](https://www.netlify.com/) which allows for things like building preview builds of PR's and branches that we want (we could have like a staging branch) and also running A/B testing and phased rollouts which could maybe further tackle this in a cleaner / simpler fashion with more automation.

**Comment by BenjaminMichaelis** [comment]
Is there anything holding us to using github pages to deploy the site?

If not we could use netlify(https://www.netlify.com/) which allows for things like building preview builds of PR's and branches that we want (we could have like a staging branch) and also running A/B testing and phased rollouts which could maybe further tackle this issue in a cleaner / simpler fashion with more automation. @Keboo

**Comment by Keboo** [comment]
I am going to close this. We are going to be moving away from hosting it on a github page and instead there is going to be a new web site for hosting this plus additional learning content.
