### ISSUE TITLE
Convert existing csv into xml

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingGuidelines#123]
Currently we have a source file in CSV format that needs to be converted to XML.

The current file exists on a branch [here](https://github.com/IntelliTect/CodingGuidelines/blob/EssentialCSharpGuidelinesCSV/EssentialCSharpGuidelines/Guidelines(8th%20Edition).csv).

We should convert it into xml that is similar to the following:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<root>
    <guideline key="Ch01_fa67753" severity="DO" section="Naming" subsection="Variables and Fields">
DO favor clarity over brevity when naming identifiers.
    </guideline>
</root>
```

Be aware there are some non-standard characters in the csv (like smart quotes) that will need to be converted.
This can be done with a script or by hand, once this is done we will not be using the csv again.

**Comment by frosch95** [comment]
Hi,
I would love to do this issue.

Where should the generated XML be stored? Next to the csv?

In the csv there is only one special character that can't be used in the xml. In the line with Ch09_39959f7 is after the enum a 0x02 which is a control char which can't be converted to something usefull. I would remove the character.

The smart quotes are ok in UTF-8 xml. I checked the generated xml in several online validators.

**Comment by frosch95** [comment]
@Keboo I can change the quotes to regular quotes inside the xml. 
Are the leading quotes in some texts important and should be kept?

**Comment by Keboo** [comment]
@frosch95 yea let's keep the quotes that are there. The source material for these is coming from the book [Essential C# 8.0](https://intellitect.com/EssentialCSharp/) which appears to have the quotes in it.
