### ISSUE TITLE
Create xlst to convert xml to markdown

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingGuidelines#124]
This requires #123 to be completed first.

We should create a new XSLT to convert the created xml file into its corresponding markdown file (located [here](https://github.com/IntelliTect/CodingGuidelines/blob/master/docs/coding/csharp.md)).

As part of this, the order of the headings should be preserved. 
For top level sections the order should be: Naming, Layout, Coding. The order of the subsections should be alphabetical, except with Miscellaneous moved to the end.

The severity attribute on the `guideline` element should get mapped to the appropriate emoji.

**Comment by twofingerrightclick** [comment]
Not sure if I took the best approach, but I wrote a dotnet app to do it.

**Comment by Keboo** [comment]
@twofingerrightclick Link to tool?

**Comment by twofingerrightclick** [comment]
https://github.com/IntelliTect/CodingGuidelines/tree/GuidelineXMLtoMD/XMLtoMD/GuidelineXmlToMD
I am working on a action that builds it and runs the executable on a push to the branch.
