### ISSUE TITLE
Exception guideline is obsolete

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingGuidelines#127]
The following exception guideline is obsolete:

> :no_entry: AVOID: general catch blocks and replace them with a catch of System.Exception.

In addition to being obsolete the recommendation likely leads people into violating another rule:

> :x: DO NOT: over-catch. Exceptions should be allowed to propagate up the call stack unless it is clearly understood how to programmatically address those errors lower in the stack.

**Comment by Keboo** [comment]
After discussion. This rule should be removed from the XML file.

⛔ AVOID: general catch blocks and replace them with a catch of System.Exception.

**Comment by RenanOD** [comment]
Thanks for the quick review! Issue can be closed after https://github.com/IntelliTect/CodingGuidelines/commit/bda86a2e9d9bd281947645d971e03885743551d9.
