### ISSUE TITLE
Naming Guidelines for fields does not match

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/CodingGuidelines#148]
[Microsoft Docs](https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/coding-style.md)

specifically static fields with s_ and thread static fields with t_. A few other minor things as well

**Comment by Keboo** [comment]
This is a guideline of MS that we want to ignore. Even in the latest versions of the .NET libraries this standard is not followed.
In many cases this also doesn't matter as the guidance is to use auto properties rather than fields so the prevalence of fields is significantly reduced.

**Comment by adamskt** [comment]
We explicitly don't want to follow Microsoft's guidelines here, as they don't even follow them themselves.  We also want to stay congruent with the Essential C# book.
