### ISSUE TITLE
Upgrade build from netcore3.1 to .NET 5.0

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/CodingGuidelines#158]
Convert from DevOps Pipeline to a Github action running .NET 5.0 as @Keboo described.

Most pressing issue I see with this right now is for example in #156 we see the build failing for the XMLtoMD code that is trying to reference .NET 5.0 after an upgrade from .net core 3.1, so to target our build to 5.0 would be a great next step.

**Comment by joeriddles** [comment]
I think @Keboo may have done this.

**Comment by Keboo** [comment]
This is only done for the XMLtoMD tool. 

The remaining work would be:
- [ ] Convert the azure-pipelines.yml to a GitHub action for building/deploying the Analyzer NuGet package
- [ ] Update the hooks so that we are no longer relying on Azure DevOps (this will require an admin to do)
