### ISSUE TITLE
`C# > Properties > Item #3` is missing the end of the sentence

### ISSUE THREAD

**Issue by joeriddles** [IntelliTect/CodingGuidelines#201]
`CONSIDER using the same casing on a property’s backing field as that used in the property, distinguishing the backing field with an “_” prefix. Do not, however, use two underscores; identifiers beginning with two underscores are reserved for the use of t`

"... are reserved for the use of t**he language**" ?

**Comment by MarkMichaelis** [comment]
This doesn't seem to conform to the general format of guidelines in that:
* There are two guidelines in one
* It isn't as succinct as is desirable
* It isn't a common enough exception to document it in the guideline.
Thoughts?

**Comment by Keboo** [comment]
Looking more at this it appears we need to regen the XML file from the manuscript.

**Comment by BenjaminMichaelis** [comment]
Updated the [manuscript to xml tool](https://github.com/IntelliTect/ManuscriptGuidelinesExtractor) to fix the character limitation issue. XML will be updated in next PR.
