### ISSUE TITLE
Azure pipeline still running?

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/CodingGuidelines#207]
Is there a reason to have the azure pipeline still running for builds if we have the github action building now?

**Comment by Keboo** [comment]
Nope, they should be removed

**Comment by BenjaminMichaelis** [comment]
Ok, I don't believe I have access to the pipelines for this project, if someone doesn't mind stopping it at some point or if I get access I can stop it as well.

**Comment by BenjaminMichaelis** [comment]
With that, we can also remove the [azure pipelines yml file](https://github.com/IntelliTect/CodingGuidelines/blob/main/azure-pipelines.yml)
