### ISSUE TITLE
Create analyzer to detect unused local variables

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingGuidelines#24]
An example implementation here: https://stackoverflow.com/questions/30982549/how-to-evaluate-local-variable-parameter-state-with-roslyn

The fix should support removing the variable declaration.

```cs
object foo = new object();
```
Fixed:
```cs
new object();
```

**Comment by myilm** [comment]
I"d like to take a shot at his.

**Comment by Keboo** [comment]
@myilm great! Let me know if you have any questions or issues.

**Comment by myilm** [comment]
Seems like I won't have time to get to this, I'm backing out so someone else has a chance. sorry!

**Comment by Keboo** [comment]
@myilm no problem. Thanks for letting me know.

**Comment by ascott18** [comment]
Exists in Roslynator (#83) as RCS1212 (https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1212.md)

**Comment by Keboo** [comment]
Will be fixed by #83
