### ISSUE TITLE
Create analyzer to suggest `is null` checks

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingGuidelines#25]
Rather than checking for `null` with `==` it is better to check with `is null` since operators can be overloaded.

We should add an analyzer to suggest this.

```cs
if (foo == null)
```
After fix:
```cs
if (foo is null)
```

**Comment by karanrn** [comment]
@Keboo Can I work on this issue?

**Comment by karanrn** [comment]
@Keboo I will work on this.

**Comment by Keboo** [comment]
@karanrn Great! Let me know if you have any questions or issues.

**Comment by OlegLviv** [comment]
unfortunately https://stackoverflow.com/questions/33456416/how-to-override-is-operator

**Comment by Keboo** [comment]
@OlegLviv the objective is not to overload the `is` operator, but to simply create an analyzer that suggests using it instead of the `==` operator.

**Comment by adamskt** [comment]
My only quibble with this is that
```
if (!(foo is null))
```
looks terrible for existence checking (inverse of null check).  I've heard `if (foo is object)` can be very performant for that, perhaps we can add a suggestion for this?

**Comment by Keboo** [comment]
@adamskt that is why I was only suggesting the change for `== null` not `!= null` because you are right it looks poor. The big reason for using `is` instead of `==` is because the `==` operator can be overridden. While `is null` is closer to `ReferenceEquals(foo, null)` except it wont accidently allow boxing.

**Comment by Keboo** [comment]
This is now being handled by intellicode. No need for the analyzer
