### ISSUE TITLE
Update the Microsoft.CodeAnalysis.VersionCheckAnalyzer

### ISSUE THREAD

**Issue by meghanmae** [IntelliTect/CodingGuidelines#270]
This package is out of date... and also depreciated. 
https://www.nuget.org/packages/Microsoft.CodeAnalysis.VersionCheckAnalyzer

Should consider updating to this package
https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/

**Comment by BenjaminMichaelis** [comment]
Done :)
