### ISSUE TITLE
Static should appear before the access modifier

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/CodingGuidelines#42]
I prefer `static` first because it stands out from the normal (which is non-static). In other words, by putting `static first, it is more noticeable than when it is buried after of `public`. 

That said, I have seen code analysis rules suggesting to put public first - making this another issue similar to private field naming perhaps.

**Comment by Keboo** [comment]
Good information on other default found here: https://stackoverflow.com/questions/191929/is-there-a-convention-to-the-order-of-modifiers-in-c

**Comment by MarkMichaelis** [comment]
By the way, I suggest the same for async - `async` should appear before the access modifier as well.  I don't have a strong opinion on the priority between `static` and `async`.  Perhaps async because it is more significant?

**Comment by Keboo** [comment]
As per discussion we will not explicitly have a standard for the ordering of these. However, we should create a code fix that allows for easily converting between these two forms.

**Comment by ascott18** [comment]
I'd say we should stick with the convention that most people use, as it is much easier to mentally parse things when they're in the "standard" order. That order being  `public static async Task Main(string[] args)`. For example, when looking at the signatures generated metadata from a DLL in VS: 

![image](https://user-images.githubusercontent.com/5017521/73672978-b96eb100-4662-11ea-9d2f-042827256263.png)


`async` should go next to the return type, as it goes hand-in-hand with the return type.

**Comment by adamskt** [comment]
Currently, we are going to stick with the visual studio defaults until momentum or a good bug-reduction case crops up.
