### ISSUE TITLE
Proposal: Add Analyzer for access modifiers

### ISSUE THREAD

**Issue by Keboo** [IntelliTect/CodingGuidelines#5]
I believe the coding standard should be to always specify your protection modifiers (on all members) to avoid any ambiguity. 

This is apparently not something that is covered in our coding standards document.

Thoughts?

**Comment by ascott18** [comment]
Exists in Roslynator (#83) as RCS1018

**Comment by Keboo** [comment]
Also worth noting this is more of a big deal with C# 8.
One of these defaults to public, the other defaults to private.
```c#
public interface IBar
{
    void Baz() { }
}

public class Bar
{
    void Baz() { }
}
```

**Comment by MarkMichaelis** [comment]
I'm okay with this.

**Comment by Keboo** [comment]
This depends on #83 being done. We should set the default severity level to Warning.

**Comment by Keboo** [comment]
#83 should resolve this
