### ISSUE TITLE
"Coding Standards" or "Coding Guidelines"

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/CodingGuidelines#86]
Perhaps a less dogmatic term for coding practices is "coding guidelines" rather than "coding standards."  Should we rename the repo accordingly or leave it as is? I ask because if we are going to change this, we should do so now.

**Comment by Keboo** [comment]
I have no problem doing this, but given that most of the industry appears to use these terms interchangeably I am not sure there a huge value.

**Comment by MarkMichaelis** [comment]
No strong preference either.  Guideline seems less dogmatic.  I believe Guideline was intentionally chosen by MS for this reason.

**Comment by adamskt** [comment]
I'm fine with changing it-- it would seem less adversarial

**Comment by Keboo** [comment]
I believe we have agreed that we should rename all instances of "Standard" to "Guideline"
