### ISSUE TITLE
Reword private fields only guideline

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/CodingGuidelines#97]
Change "DO only declare instance fields that are public or protected." to  "DO declare all instance fields as private."

**Comment by MarkMichaelis** [comment]
I confess I couldn't find this in our guidelines so perhaps this is just a suggestion to put it there. :)

**Comment by Keboo** [comment]
I have no objections to adding this.

**Comment by Keboo** [comment]
Closing as this only was found in the Essential C# book
